# Generated by Django 4.1.5 on 2023-01-23 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="boat_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boat_name",
                    models.CharField(
                        choices=[
                            ("Coble", "Coble"),
                            ("Jet Ski", "Jet Ski"),
                            ("Small Yacht", "Small Yacht"),
                            ("Inflatable Boat", "Inflatable Boat"),
                            ("Speedboat", "Speedboat"),
                            ("Big Yacht", "Big Yacht"),
                        ],
                        max_length=50,
                    ),
                ),
                ("capacity", models.PositiveIntegerField()),
                ("fee", models.PositiveIntegerField()),
                ("postdate", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="user_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("contact", models.PositiveBigIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="ride_booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_of_pass", models.PositiveIntegerField()),
                ("doj", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("contact", models.PositiveBigIntegerField()),
                (
                    "boat_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="boat.boat_details",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="boat.user_details",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AMT", models.PositiveIntegerField(null=True)),
                (
                    "boat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="boat.boat_details",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="boat.user_details",
                    ),
                ),
            ],
        ),
    ]
