# Generated by Django 4.1.5 on 2023-01-26 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_details",
            name="name",
            field=models.CharField(
                max_length=25,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z A-Z]*$", "Only Alphabet characters are allowed."
                    )
                ],
            ),
        ),
    ]
