# Generated by Django 4.1.5 on 2023-01-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boat", "0002_alter_user_details_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="user",
            new_name="usern",
        ),
    ]
