# Generated by Django 4.1.5 on 2023-01-27 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boat", "0003_rename_user_invoice_usern"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride_booking",
            name="boat_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="boat.boat_details",
            ),
        ),
    ]
