# Generated by Django 4.1.5 on 2023-01-27 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boat", "0004_alter_ride_booking_boat_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride_booking",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="boat.user_details",
            ),
        ),
    ]
