# Generated by Django 4.1.5 on 2023-01-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boat", "0005_alter_ride_booking_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride_booking",
            name="status",
            field=models.CharField(
                choices=[("paid", "paid"), ("pending", "pending")],
                default="pending",
                max_length=25,
            ),
        ),
    ]
