# Generated by Django 4.1.5 on 2023-01-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boat", "0006_ride_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride_booking",
            name="status",
            field=models.CharField(
                choices=[("Paid", "Paid"), ("Pending", "Pending")],
                default="pending",
                max_length=25,
            ),
        ),
    ]
